### ISSUE TITLE
More detailed instructions PLZ

### ISSUE THREAD

**Issue by MadFlyFish** [gilzoide/godot-input-key-event-grabber#1]
I will be appreciate it if more detailed instructions are offered :)

**Comment by gilzoide** [comment]
Hi there! Sorry about the lack of documentation, it was the kind of project that one makes for using elsewhere and don't tidy up properly until later =P

I just added some documentation, I hope it solves your request! Now there are:
- Sample scene with usage example of changing a ShortCut key binding with the key grabber
- README section about how to install the addon (also linking to the oficial Godot docs about it)
- README section with the public API (there is not much to it, but this script is indeed this simple)
- Some GIFs on README of the inspector plugin, modifying InputEventKey Resources by issuing key combos instead of looking up scancode and unicode numeric values
